---

- name: Install and configure Restic backups for OriginTrail nodes...
  hosts: all
  gather_facts: no

  tasks:
    - name: Add backup schedule to cron (every 6 hours)
      cron:
        name: "Restic backup"
        minute: "0"
        hour: "*/6"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/root/restic/restic-backup.sh"
