---
####################################################################################
# Ansible Users. All commands below assume you are root when running these commands:
#
# If you login as root on the VPS with a password:
# anible-playbook -k ansible-install-restic.yml
#
# If you login as root on the VPS with an SSH key:
# anible-playbook ansible-install-restic.yml
#
# If you login as a sudo user account on the VPS with a password:
# anible-playbook -u REPLACE_WITH_USERNAME -b -k -K -ansible-install-restic.yml
#
# If you login as a sudo user account on the VPS with an SSH key:
# anible-playbook -u REPLACE_WITH_USERNAME -b -K ansible-install-restic.yml
#
####################################################################################

- name: Install and configure Restic backups for OriginTrail nodes...
  hosts: all
  gather_facts: no

  tasks:
  - name: Clone OT-Smoothbrain-Backup git repository
    git:
      repo: 'https://github.com/calr0x/OT-Smoothbrain-Backup.git'
      dest: /root/OT-Smoothbrain-Backup
      force: yes

  - name: Copy config file
    copy:
      src: /root/OT-Smoothbrain-Backup/config.sh
      dest: /root/OT-Smoothbrain-Backup

  - name: Set files to be executable
    file:
      path: '{{ item }}'
      mode: '0700'
    loop:
      - '/root/OT-Smoothbrain-Backup/data/link-merged.sh'
      - '/root/OT-Smoothbrain-Backup/data/send.sh'
      - '/root/OT-Smoothbrain-Backup/restic'
      - '/root/OT-Smoothbrain-Backup/restic-backup.sh'
      - '/root/OT-Smoothbrain-Backup/restic-cleanup.sh'

  - name: Link merged directory to host
    shell: /root/OT-Smoothbrain-Backup/data/link-merged.sh

  - name: Add backup schedule to cron (every 6 hours)
    cron:
      name: "Restic backup"
      minute: "0"
      hour: "*/6"
      day: "*"
      month: "*"
      weekday: "*"
      job: "/root/OT-Smoothbrain-Backup/restic-backup.sh"

  - name: Execute initial backup
    shell: /root/OT-Smoothbrain-Backup/restic-backup.sh
