---

- name: Install and configure Restic backups for OriginTrail nodes...
  hosts: all
  gather_facts: no

  tasks:
    - name: Create restic folder in /root
      file:
        path: /root/restic
        state: directory
        mode: '0600'

    - name: Copying the restic application
      copy:
        src: ~/Smoothbrain-OT-Backup/restic
        dest: /root/restic/
        owner: root
        group: root
        mode: '0700'

    - name: Copy docker folder link script file to server
      copy:
        src: ~/Smoothbrain-OT-Backup/data/link-merged.sh
        dest: /root/restic/
        owner: root
        group: root
        mode: '0700'

    - name: Link merged directory to host
      shell: ~/restic/link-merged.sh

    - name: Copy restic-backup file to server
      copy:
        src: ~/Smoothbrain-OT-Backup/restic-backup.sh
        dest: /root/restic/
        owner: root
        group: root
        mode: '0700'

    - name: Copy send.sh file to server
      copy:
        src: ~/Smoothbrain-OT-Backup/data/send.sh
        dest: /root/restic/
        owner: root
        group: root
        mode: '0700'

    - name: Copy restic-cleanup file to server
      copy:
        src: ~/Smoothbrain-OT-Backup/restic-cleanup.sh
        dest: /root/restic/
        owner: root
        group: root
        mode: '0700'

    - name: Copy restic config file to server
      copy:
        src: ~/Smoothbrain-OT-Backup/config.sh
        dest: /root/restic/
        owner: root
        group: root
        mode: '0600'

    - name: Add backup schedule to cron (every 6 hours)
      cron:
        name: "Restic backup"
        minute: "0"
        hour: "*/6"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/root/restic/restic-backup.sh"

    - name: Create repo
      command:
        chdir: /root/Smoothbrain-OT-Backup/
        cmd: restic --init

    - name: Execute initial backup
      shell: /root/restic/restic-backup.sh
